<?php
// +----------------------------------------------------------------------
// | [RhaPHP System] Copyright (c) 2017 http://www.rhaphp.com/
// +----------------------------------------------------------------------
// | [RhaPHP] 并不是自由软件,你可免费使用,未经许可不能去掉RhaPHP相关版权
// +----------------------------------------------------------------------
// | Author: Geeson <qimengkeji@vip.qq.com>
// +----------------------------------------------------------------------

namespace app\sys\com\builder\api\v1\controller;

use App\Admin\Controllers\Controller;
use com\builder\common\v1\logic\TableCommon;
use think\Db;
use think\facade\Request;

class Test extends Controller {
    public $adminLogin = false;

    public function initialize()
    {
	    $param = Request::param();
	    $act = $param['act'];
	    $this->isCheckLogin = !in_array($act, ['index']);
        //parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index() {
    	// http://wx.uujia.net/uustart1/test/miniapp/v1/test/index
    	echo 111111111112;
	    die();
    }
	
	public function ttt() {
		$tableCommon = new TableCommon();
		echo $tableCommon->test();
	}
}